FROM apache/airflow:2.8.0-python3.10

USER root

# Install system dependencies for NetCDF, Aria2, etc.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libnetcdf-dev \
    libhdf5-dev \
    aria2 \
    procps \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python packages
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
